### Numpy Arrays 

In [12]:
import numpy as np

In [13]:
list = [1,2,3,4,5]

In [14]:
arr = np.array(list)

In [16]:
arr

array([1, 2, 3, 4, 5])

In [21]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np_array = np.array(my_mat)

In [23]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arr = np.arange(1,20,2).reshape(2,5)

In [35]:
arr.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [37]:
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [45]:
arr = np.zeros((2,4))  # Pass single number for one dimensional array and tuple for 2 dimension arrays

In [46]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
arr = np.linspace(1,20,5)

In [82]:
arr

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [85]:
np.eye(4)  # Returns an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [104]:
np.random.rand(10)  # Returns random numbers uniformly distributed between 0 and 1

array([0.89079783, 0.97153961, 0.87321298, 0.56352205, 0.52907207,
       0.54010468, 0.59931285, 0.27413284, 0.41795589, 0.55075931])

In [106]:
np.random.rand(5,5)

array([[0.13001459, 0.66798298, 0.27009882, 0.46424513, 0.60051461],
       [0.28272155, 0.89833974, 0.97050774, 0.58537616, 0.50182705],
       [0.77040141, 0.95995494, 0.46938428, 0.59268115, 0.32704374],
       [0.74040986, 0.91263689, 0.97700564, 0.3489674 , 0.81538155],
       [0.66519187, 0.73461826, 0.16849863, 0.47852409, 0.99348787]])

In [116]:
np.random.randn(5,5)  # Returns number from standard normal distribution (Gaussian)

array([[ 1.52353974, -2.37243693, -1.21552026,  1.02397679, -1.06285461],
       [-0.43447456,  0.65232564, -0.15987206, -0.43100003,  0.53762894],
       [-0.71831659,  1.5615153 ,  0.98126995,  0.36963474, -1.99910748],
       [-1.46917901, -1.70824949,  0.30260494,  0.64500823, -0.34729489],
       [-0.81460026, -1.85448146, -0.52630698, -1.46773371,  0.71258491]])

In [152]:
arr  =np.random.randint(1,100,10).reshape(2,5)

In [153]:
arr

array([[29, 87, 31, 27, 68],
       [96, 58, 29, 61, 10]])

In [154]:
arr.max()

96

In [155]:
arr.min()

10

In [159]:
arr.argmax()  # returns the index of max number

5

In [161]:
arr.argmin() # returns the index of min number

9

In [164]:
arr.dtype

dtype('int32')

In [166]:
from numpy.random import randint

In [183]:
randint(10)

9

### NumPy Indexing and Selection

In [185]:
import numpy as np

In [222]:
arr = np.arange(0,11)

In [223]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [197]:
arr[0]  # Array indexing. Similar to List indexing

0

In [195]:
arr[1:5]

array([1, 2, 3, 4])

In [198]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [213]:
arr[::-1]  #reversing an array

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [224]:
slice_of_arr = arr[:5]  #Slice of the array will create a view. Changing this array will affect the original array
slice_of_arr

array([0, 1, 2, 3, 4])

In [231]:
slice_of_arr = arr[:5].copy()  #To avoid affecting the original array, use copy function

In [227]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [228]:
slice_of_arr[:] = 100   #Broadcasting an array

In [230]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [233]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [235]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [237]:
arr_2d[0][0]  #Double bracket notation. 

1

In [241]:
arr_2d[0,0]  #Single bracket notation. This is the preferred method

1

In [249]:
arr_2d[:2,1:] #slicing of the matrix

array([[2, 3],
       [5, 6]])

### Conditional selection of arrays

In [253]:
arr = np.arange(11)

In [255]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [261]:
boolean = arr > 5  #Returns a boolean value

In [263]:
arr[boolean] #selecting elements from an array based on a condition

array([ 6,  7,  8,  9, 10])

In [265]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

###  Numpy Operations

* Array with Array
* Array with scalars
* Universal Array functions

In [268]:
import numpy as np

In [270]:
arr = np.arange(0,11)

In [273]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [276]:
# Adding 2 arrays element by element
arr = arr + arr

In [277]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [279]:
# Adding arrays to a scalar (single number)
arr = arr * 2

In [280]:
arr

array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [289]:
arr2 = np.arange(2,13)

In [291]:
arr3 = arr + arr2

In [293]:
arr3

array([ 2, 11, 20, 29, 38, 47, 56, 65, 74, 83, 92])

In [296]:
arr / arr  #python throws a warning when there is a divide by zero issue

C:\Users\118472\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [299]:
arr ** 2

array([   0,   64,  256,  576, 1024, 1600, 2304, 3136, 4096, 5184, 6400],
      dtype=int32)

### Universal array function

In [302]:
np.sqrt(arr)

array([0.        , 2.82842712, 4.        , 4.89897949, 5.65685425,
       6.32455532, 6.92820323, 7.48331477, 8.        , 8.48528137,
       8.94427191])

In [305]:
np.exp(arr)

array([1.00000000e+00, 2.98095799e+03, 8.88611052e+06, 2.64891221e+10,
       7.89629602e+13, 2.35385267e+17, 7.01673591e+20, 2.09165950e+24,
       6.23514908e+27, 1.85867175e+31, 5.54062238e+34])

In [307]:
np.max(arr)

80

In [309]:
np.min(arr)

0

In [311]:
np.sin(arr)

array([ 0.        ,  0.98935825, -0.28790332, -0.90557836,  0.55142668,
        0.74511316, -0.76825466, -0.521551  ,  0.92002604,  0.25382336,
       -0.99388865])

In [317]:
np.log(arr)

C:\Users\118472\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 2.07944154, 2.77258872, 3.17805383, 3.4657359 ,
       3.68887945, 3.87120101, 4.02535169, 4.15888308, 4.27666612,
       4.38202663])